# -----------------------------------------------------------------------------
# Nord skin
# -----------------------------------------------------------------------------

# Styles...
foreground: &foreground "#DADEE8"
background: &background "#4d201d"
current_line: &current_line "#383D4A"
selection: &selection "#D9DEE8"
comment: &comment "#8891A7"
cyan: &cyan "#88C0D0"
green: &green "#A3BE8C"
orange: &orange "#D08770"
blue: &blue "#81A1C1"
magenta: &magenta "#B48EAD"
red: &red "#BF616A"
yellow: &yellow "#EBCB8B"

# Skin...
k9s:
  # General K9s styles
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *magenta
  # Command prompt styles
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *orange
  # ClusterInfoView styles.
  info:
    fgColor: *blue
    sectionColor: *foreground
  # Dialog styles.
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *magenta
    buttonFocusFgColor: *yellow
    buttonFocusBgColor: *blue
    labelFgColor: *orange
    fieldFgColor: *foreground
  frame:
    # Borders styles.
    border:
      fgColor: *selection
      focusColor: *current_line
    menu:
      fgColor: *foreground
      keyColor: *blue
      # Used for favorite namespaces
      numKeyColor: *blue
    # CrumbView attributes for history navigation.
    crumbs:
      fgColor: *foreground
      bgColor: *current_line
      activeColor: *current_line
    # Resource status and update styles
    status:
      newColor: *cyan
      modifyColor: *magenta
      addColor: *green
      errorColor: *red
      highlightColor: *orange
      killColor: *comment
      completedColor: *comment
    # Border title styles.
    title:
      fgColor: *foreground
      bgColor: *current_line
      highlightColor: *orange
      counterColor: *magenta
      filterColor: *blue
  views:
    # Charts skins...
    charts:
      bgColor: *background
      defaultDialColors:
        - *magenta
        - *red
      defaultChartColors:
        - *magenta
        - *red
    # TableView attributes.
    table:
      fgColor: *foreground
      bgColor: *background
      # Header row styles.
      header:
        fgColor: *foreground
        bgColor: *background
        sorterColor: *cyan
    # Xray view attributes.
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *current_line
      graphicColor: *magenta
      showIcons: false
    # YAML info styles.
    yaml:
      keyColor: *blue
      colonColor: *magenta
      valueColor: *foreground
    # Logs styles.
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *magenta
        toggleOnColor: *magenta
        toggleOffColor: *blue
    help:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *red